dataset_dir: "dataset/lafan1"
window_length: 61
window_offset: 1

epochs: 30
batch_size: 32
lr: 1e-4
weight_decay: 1e-4
restart_period: 10
restart_mult: 2

phase_channels: 8

save_dir: "save/lafan1/PAE"