dataset_dir: "dataset/lafan1"

window_length: 101
window_offset: 20
context_frames: 10

# --- Key Architectural Flags ---
use_phase: true
use_traj: true
use_score: true
decoupled_traj_encoder: true      # 启用独立的轨迹编码器
decoupled_phase_encoder: false    # 禁用独立的相位编码器，相位将与运动一起处理
decoupled_traj_decoder: true      # 启用独立的轨迹解码器
use_foot_consistency: true        # 启用足部一致性损失
# ---

save_dir: "save/lafan1/RefineNet-traj-enc-dec-fc"
save_interval: 50
val_interval: 10

batch_size: 64
epochs: 1000
warmup_iters: 8000


min_trans: 5
max_trans: 90
contact_joints: [ "mixamorig:LeftFoot", "mixamorig:LeftToeBase", "mixamorig:RightFoot", "mixamorig:RightToeBase" ]
contact_threshold: 1e-4
midway_amount: 0.1
midway_prob: 0.5
min_kf_dist: 5
max_kf_dist: 15

d_mask: 1
n_layer: 6
n_head: 8
d_model: 512
d_head: 64
d_pff_inner: 512
d_encoder_h: 512
d_decoder_h: 512
d_gating_h: 512
dropout: 0.0
pre_lnorm: true
atten_bias: false
residual: true

weight_rot: 1.0
weight_pos: 2.0
weight_phase: 0.5
weight_traj: 0.5
weight_contact: 0.1
weight_score: 1.0
weight_foot_consistency: 0.1     # 足部一致性损失权重